#ifndef ZERO_HW_GPIOA_H
#define ZERO_HW_GPIOA_H

/**
 * @file hw_gpioa.h
 * @brief Auto-generated hardware register map for GPIOA.
 * Generated by ZeroEmbedded SVD Codegen tool from CMSIS-SVD.
 * Description: General-purpose I/O Port A
 */

#include "zero/types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    volatile uint32_t   MODER       ; /*!< 0x00: GPIO port mode register */
    volatile uint32_t   OTYPER      ; /*!< 0x04: GPIO port output type register */
    volatile uint32_t   OSPEEDR     ; /*!< 0x08: GPIO port output speed register */
    volatile uint32_t   PUPDR       ; /*!< 0x0C: GPIO port pull-up/pull-down register */
    volatile uint32_t   IDR         ; /*!< 0x10: GPIO port input data register */
    volatile uint32_t   ODR         ; /*!< 0x14: GPIO port output data register */
    volatile uint32_t   BSRR        ; /*!< 0x18: GPIO port bit set/reset register */
} fw_hw_gpioa_t;

#define GPIOA_BASE ((uintptr_t)0x40020000)
#define GPIOA ((volatile fw_hw_gpioa_t*)GPIOA_BASE)

#ifdef __cplusplus
}
#endif

#endif /* ZERO_HW_GPIOA_H */
