#ifndef ZERO_HW_USART1_H
#define ZERO_HW_USART1_H

/**
 * @file hw_usart1.h
 * @brief Auto-generated hardware register map for USART1.
 * Generated by ZeroEmbedded SVD Codegen tool from CMSIS-SVD.
 * Description: Universal synchronous asynchronous receiver transmitter
 */

#include "zero/types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    volatile uint32_t   SR          ; /*!< 0x00: Status register */
    volatile uint32_t   DR          ; /*!< 0x04: Data register */
    volatile uint32_t   BRR         ; /*!< 0x08: Baud rate register */
    volatile uint32_t   CR1         ; /*!< 0x0C: Control register 1 */
} fw_hw_usart1_t;

#define USART1_BASE ((uintptr_t)0x40011000)
#define USART1 ((volatile fw_hw_usart1_t*)USART1_BASE)

#ifdef __cplusplus
}
#endif

#endif /* ZERO_HW_USART1_H */
