#!/usr/bin/env python3
"""
ZeroEmbedded CMSIS-SVD Hardware Register Code Generator
Parses standard ARM CMSIS-SVD XML files and generates type-safe C register structs.
"""

import sys
import os
import xml.etree.ElementTree as ET
from pathlib import Path

HEADER_TEMPLATE = """#ifndef {guard}
#define {guard}

/**
 * @file {filename}
 * @brief Auto-generated hardware register map for {peripheral_name}.
 * Generated by ZeroEmbedded SVD Codegen tool from CMSIS-SVD.
 * Description: {description}
 */

#include "zero/types.h"

#ifdef __cplusplus
extern "C" {{
#endif

typedef struct {{
{registers}
}} {struct_name};

#define {peripheral_name}_BASE ((uintptr_t){base_address})
#define {peripheral_name} ((volatile {struct_name}*){peripheral_name}_BASE)

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""

def parse_int(text: str) -> int:
    text = text.strip()
    if text.startswith(("0x", "0X")):
        return int(text, 16)
    return int(text)

def generate_peripheral(periph_elem, out_dir: Path) -> str:
    name = periph_elem.findtext("name", "UNKNOWN").upper()
    base_addr = periph_elem.findtext("baseAddress", "0x40000000").strip()
    desc = periph_elem.findtext("description", f"{name} Peripheral").strip()

    regs_elem = periph_elem.find("registers")
    if regs_elem is None:
        return ""

    registers = []
    for reg in regs_elem.findall("register"):
        r_name = reg.findtext("name", "REG").strip()
        r_offset = parse_int(reg.findtext("addressOffset", "0"))
        r_desc = reg.findtext("description", "").strip()
        r_size = parse_int(reg.findtext("size", "32"))
        registers.append({
            "name": r_name,
            "offset": r_offset,
            "desc": r_desc,
            "size": r_size
        })

    # Sort registers by address offset
    registers.sort(key=lambda x: x["offset"])

    reg_lines = []
    current_offset = 0
    reserved_idx = 0

    for reg in registers:
        offset = reg["offset"]
        size_bytes = max(1, reg["size"] // 8)

        # Insert padding if gap exists between registers
        if offset > current_offset:
            gap = offset - current_offset
            gap_words = gap // 4
            if gap % 4 == 0 and gap_words > 0:
                if gap_words == 1:
                    reg_lines.append(f"    volatile uint32_t   RESERVED{reserved_idx}  ; /*!< Gap: 0x{current_offset:02X} */")
                    reserved_idx += 1
                else:
                    reg_lines.append(f"    volatile uint32_t   RESERVED{reserved_idx}[{gap_words}]; /*!< Gap: 0x{current_offset:02X}..0x{offset:02X} */")
                    reserved_idx += 1
            else:
                reg_lines.append(f"    volatile uint8_t    RESERVED{reserved_idx}[{gap}]; /*!< Gap: 0x{current_offset:02X} */")
                reserved_idx += 1
            current_offset = offset

        c_type = "uint32_t" if reg["size"] == 32 else "uint16_t" if reg["size"] == 16 else "uint8_t"
        reg_lines.append(f"    volatile {c_type:10} {reg['name']:12}; /*!< 0x{offset:02X}: {reg['desc']} */")
        current_offset = offset + size_bytes

    guard = f"ZERO_HW_{name}_H"
    filename = f"hw_{name.lower()}.h"
    struct_name = f"fw_hw_{name.lower()}_t"

    content = HEADER_TEMPLATE.format(
        guard=guard,
        filename=filename,
        peripheral_name=name,
        description=desc,
        registers="\n".join(reg_lines),
        struct_name=struct_name,
        base_address=base_addr
    )

    out_file = out_dir / filename
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(content)

    return str(out_file)

def process_svd(svd_path: str, output_dir: str):
    p = Path(svd_path)
    if not p.is_file():
        print(f"[ERROR] SVD file not found: {svd_path}")
        sys.exit(1)

    out_p = Path(output_dir)
    out_p.mkdir(parents=True, exist_ok=True)

    tree = ET.parse(p)
    root = tree.getroot()
    device_name = root.findtext("name", "DEVICE")

    print(f"\n[SVD CODEGEN] Parsing CMSIS-SVD: '{svd_path}' (Device: {device_name})")

    generated = []
    for periph in root.findall(".//peripheral"):
        header_path = generate_peripheral(periph, out_p)
        if header_path:
            generated.append(header_path)

    print(f"[SVD CODEGEN] Successfully generated {len(generated)} register header(s) in: {out_p}\n")
    for f in generated:
        print(f"  -> {f}")
    print()

def main():
    if len(sys.argv) < 2:
        default_svd = Path(__file__).parent / "stm32_sample.svd"
        default_out = Path(__file__).resolve().parent.parent.parent / "hal"
        process_svd(str(default_svd), str(default_out))
    else:
        svd_file = sys.argv[1]
        out_dir = sys.argv[2] if len(sys.argv) > 2 else "hal"
        process_svd(svd_file, out_dir)

if __name__ == "__main__":
    main()
