#!/usr/bin/env python3
"""
ZeroEmbedded Hardware Code Generator (Phase 7)
Generates type-safe C register structs and driver headers from peripheral descriptions.
"""

import sys
import json
from pathlib import Path

HEADER_TEMPLATE = """#ifndef {guard}
#define {guard}

/**
 * @file {filename}
 * @brief Auto-generated hardware register map for {peripheral_name}.
 * Generated by ZeroEmbedded SVD Codegen tool.
 */

#include "zero/types.h"

#ifdef __cplusplus
extern "C" {{
#endif

typedef struct {{
{registers}
}} {struct_name};

#define {peripheral_name}_BASE ((uintptr_t){base_address})
#define {peripheral_name} ((volatile {struct_name}*){peripheral_name}_BASE)

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""

def generate_peripheral_header(desc: dict) -> str:
    name = desc["name"].upper()
    base_addr = desc.get("base_address", "0x40000000")
    guard = f"ZERO_HW_{name}_H"
    struct_name = f"fw_hw_{name.lower()}_t"
    
    reg_lines = []
    for reg in desc.get("registers", []):
        reg_name = reg["name"]
        reg_type = reg.get("type", "uint32_t")
        comment = reg.get("description", "")
        reg_lines.append(f"    volatile {reg_type:10} {reg_name:12}; /*!< 0x{reg.get('offset', 0):02X}: {comment} */")

    return HEADER_TEMPLATE.format(
        guard=guard,
        filename=f"hw_{name.lower()}.h",
        peripheral_name=name,
        registers="\n".join(reg_lines),
        struct_name=struct_name,
        base_address=base_addr
    )

def main():
    sample_desc = {
        "name": "GPIOA",
        "base_address": "0x40020000",
        "registers": [
            {"name": "MODER", "offset": 0x00, "description": "GPIO port mode register"},
            {"name": "OTYPER", "offset": 0x04, "description": "GPIO port output type register"},
            {"name": "OSPEEDR", "offset": 0x08, "description": "GPIO port output speed register"},
            {"name": "PUPDR", "offset": 0x0C, "description": "GPIO port pull-up/pull-down register"},
            {"name": "IDR", "offset": 0x10, "description": "GPIO port input data register"},
            {"name": "ODR", "offset": 0x14, "description": "GPIO port output data register"},
            {"name": "BSRR", "offset": 0x18, "description": "GPIO port bit set/reset register"}
        ]
    }

    out_dir = Path("E:/15. Other/ZeroUniverse/ZeroEmbedded/hal")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    header_content = generate_peripheral_header(sample_desc)
    target_file = out_dir / "hw_gpioa.h"
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(header_content)

    print(f"[CODEGEN] Generated hardware register header: {target_file}")

if __name__ == "__main__":
    main()
